-- 0002 - the floor a lead can be WRITTEN on. Five DDL changes; the sixth
-- piece of the same job is an insert ORDER and lives in `seed.ts`.
--
-- drizzle-kit generated every DDL statement below, the lower() functional
-- index included - unlike 0001, none of the DDL needed rewriting. ONE
-- statement is hand-written and drizzle-kit will not reproduce it: the
-- backfill in step 4. If this file is ever regenerated, put it back.
--
--  1. sales.lead_code_seq        - `code` is a text PK with no DEFAULT, so
--     nothing could create a lead without already knowing a free code. Starts
--     at 201 because the frozen DAS Vina fixture owns LD-0101 ... LD-0200 and
--     seed writes those literally; the counter must never hand one back out.
--     The `LD-%04d` format is applied in `LeadRepository.nextCode()`, not as a
--     column DEFAULT - see the `leadCodeSeq` docblock in `lead.schema.ts`.
--
--  2. lead.motion               - who made the first move, one of six. NULL
--     for the fixture: it predates the idea of an intake door, and a guessed
--     value would be read as real data on the Performance screen.
--
--  3. lead_email_live_idx       - moved from raw `email` to `lower(email)`.
--     `An@x.vn` and `an@x.vn` are one mailbox; on the raw index they slipped
--     through as two live leads.
--
--  4. lead_code_object_code_fk  - `lead.code` now points at
--     `platform.object(code)`. Without it a lead written without its mirror
--     row is valid and INVISIBLE to E1: ContextRail renders empty (luat 10)
--     and nothing turns red. Consequence: every writer, `seed.ts` included,
--     inserts platform.object BEFORE sales.lead in one transaction.
--
--     Preceded by a HAND-WRITTEN backfill, because this database was not
--     empty when the key arrived: 100 seeded leads had no mirror row and
--     Postgres rejected the constraint on the first of them. The backfill
--     DERIVES each row from the lead it mirrors - same fields
--     `lead.mapper.ts#toRef` reads - so it invents nothing; `ON CONFLICT DO
--     NOTHING` makes it a no-op on a database that is already consistent.
--
--  5. lead_no_blank             - `contact_channel` joins the 15 columns
--     already covered. It feeds slot 5 of the generated `required_filled`
--     (`phone IS NOT NULL OR contact_channel IS NOT NULL`), and '' is NOT
--     NULL - so a blank channel counted the slot as filled and inflated the
--     MQL gate.
--
-- Live-database note: the handover doc recorded these tables as empty; they
-- were not - `sales.lead` held the 100 seeded fixture rows. The widened CHECK
-- accepts them unchanged (no seeded row carries ''), and the foreign key is
-- satisfied by the backfill in step 4.

CREATE SEQUENCE "sales"."lead_code_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 201 CACHE 1;--> statement-breakpoint
ALTER TABLE "sales"."lead" DROP CONSTRAINT "lead_no_blank";--> statement-breakpoint
DROP INDEX "sales"."lead_email_live_idx";--> statement-breakpoint
ALTER TABLE "sales"."lead" ADD COLUMN "motion" text;--> statement-breakpoint
-- HAND-WRITTEN, NOT GENERATED BY drizzle-kit. Keep it if this file is
-- regenerated. Every existing lead gets the mirror row the key below now
-- demands, derived from the lead itself: 'LD'/'Sales' are what
-- `lead.mapper.ts#toRef` stamps on a lead object, `owner` is the actor's
-- display NAME because that is what E2's scope axis still compares against,
-- and `state` is the stage key. No column is read from anywhere else.
INSERT INTO "platform"."object" ("code", "kind", "branch", "label", "owner", "state", "amount")
SELECT l."code", 'LD', 'Sales', l."company", a."name", l."stage", NULL
  FROM "sales"."lead" l
  LEFT JOIN "platform"."actor" a ON a."id" = l."owner_id"
ON CONFLICT ("code") DO NOTHING;--> statement-breakpoint
ALTER TABLE "sales"."lead" ADD CONSTRAINT "lead_code_object_code_fk" FOREIGN KEY ("code") REFERENCES "platform"."object"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "lead_email_live_idx" ON "sales"."lead" USING btree (lower("email")) WHERE "exit_reason" IS NULL;--> statement-breakpoint
ALTER TABLE "sales"."lead" ADD CONSTRAINT "lead_no_blank" CHECK ("company" <> '' AND "legal_name" <> '' AND "tax_code" <> '' AND "address" <> '' AND "province" <> '' AND "main_product" <> '' AND "contact_name" <> '' AND "contact_title" <> '' AND "email" <> '' AND "phone" <> '' AND "contact_channel" <> '' AND "pain" <> '' AND "current_stack" <> '' AND "decision_maker" <> '' AND "approver" <> '' AND "source" <> '');