import type { IconSvgElement } from '@hugeicons/react'

/**
 * Aurora icon registry.
 *
 * Screens consume glyphs from @pv/ui instead of depending on an icon vendor.
 * That keeps the visual family swappable and leaves size/stroke enforcement to
 * the <Icon> gateway. Hugeicons keeps a number of compatibility aliases, so
 * the public names stay semantic and concise.
 */
export type IconGlyph = IconSvgElement

export {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Bold,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleX,
  ClipboardList,
  Code,
  Coins,
  Copy,
  Download,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  FileCheck,
  FileText,
  FileUp,
  Filter,
  FolderOpen,
  Globe,
  Link01Icon as Link,
  Handshake,
  Hash,
  House,
  ImagePlus,
  Inbox,
  Info,
  Italic,
  Linkedin,
  List,
  ListChecks,
  Lock,
  Mail,
  MailCheck,
  MailOpen,
  MailX,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Minus,
  Octagon,
  Orbit,
  Package,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  PhoneIncoming,
  PhoneOutgoing,
  Pin,
  Plug,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  Save,
  ScanLine,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  UserMinus,
  UserPlus,
  Users,
  Wallet,
  X,
  Zap,
} from '@hugeicons/core-free-icons'

// Semantic aliases for familiar names that Hugeicons does not expose directly.
export {
  Building02Icon as Building,
  ChartAnalysisIcon as ChartAnalysis,
  CheckmarkCircle02Icon as CheckCircle2,
  CheckmarkCircle02Icon as CircleCheckBig,
  Contact01Icon as Contact,
  ContactBookIcon as ContactBook,
  FileSpreadsheetIcon as FileSpreadsheet,
  GaugeIcon as Gauge,
  Key01Icon as KeyRound,
  Logout03Icon as LogOut,
  Moon02Icon as Moon,
  Route01Icon as Route,
  CheckmarkSquare02Icon as SquareCheckBig,
  Sun03Icon as Sun,
  TriangleAlertIcon as TriangleAlert,
  UnavailableIcon as Ban,
  UserAdd01Icon as UserRoundPlus,
  UserGroupIcon as UsersRound,
} from '@hugeicons/core-free-icons'
