import type { ContactChannel, LeadCategory } from '@pv/contracts'

/** The twenty chip-industry companies of the demo book and the people we know
 *  at each. Split from `seed-book.ts` by length only; the header there says
 *  what is real and what is invented. */

export type ContactSeed = {
  name: string
  title: string
  mail: string
  phone: string
  channel: ContactChannel
}

export type AccountSeed = {
  key: string
  name: string
  legalName: string
  domain: string
  address: string
  province: string
  category: LeadCategory
  mainProduct: string
  headcount: number
  plants: number
  ownerId: string | null
  note?: string
  /** People we know there; each lead picks its own, see `JourneySeed.contacts`. */
  contacts: ContactSeed[]
}

export const ACCOUNTS: AccountSeed[] = [
  {
    key: 'amkor',
    name: 'Amkor Technology Việt Nam',
    legalName: 'Công ty TNHH Amkor Technology Việt Nam',
    domain: 'amkor.example',
    address: 'KCN Yên Phong II-C, Yên Phong',
    province: 'Bắc Ninh',
    category: 'chip',
    mainProduct: 'Đóng gói và kiểm thử chip (OSAT) — SiP, flip-chip',
    headcount: 3200,
    plants: 1,
    ownerId: 'u-am',
    note: 'Khách đầu tiên ngành OSAT. Go-live MES giai đoạn 1 xong, đang bàn mở rộng sang bảo trì.',
    contacts: [
      {
        name: 'Nguyễn Thanh Tùng',
        title: 'Giám đốc Nhà máy',
        mail: 'tung.nguyen',
        phone: '0912 418 305',
        channel: 'email',
      },
      {
        name: 'Park Ji-hoon',
        title: 'Trưởng phòng IT',
        mail: 'jihoon.park',
        phone: '0936 220 781',
        channel: 'linkedin',
      },
      {
        name: 'Lê Thu Hà',
        title: 'Trưởng phòng Bảo trì',
        mail: 'ha.le',
        phone: '0983 551 902',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'hana',
    name: 'Hana Micron Vina',
    legalName: 'Công ty TNHH Hana Micron Vina',
    domain: 'hanamicron.example',
    address: 'KCN Vân Trung, Việt Yên',
    province: 'Bắc Giang',
    category: 'chip',
    mainProduct: 'Đóng gói chip nhớ DRAM và NAND',
    headcount: 2600,
    plants: 1,
    ownerId: 'u-am',
    contacts: [
      {
        name: 'Kim Min-seok',
        title: 'Phó Giám đốc Sản xuất',
        mail: 'minseok.kim',
        phone: '0904 310 662',
        channel: 'email',
      },
      {
        name: 'Trần Minh Đức',
        title: 'Kỹ sư trưởng Quy trình',
        mail: 'duc.tran',
        phone: '0975 128 440',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'qorvo',
    name: 'Qorvo Việt Nam',
    legalName: 'Công ty TNHH Qorvo Việt Nam',
    domain: 'qorvo.example',
    address: 'KCN Yên Phong, Yên Phong',
    province: 'Bắc Ninh',
    category: 'chip',
    mainProduct: 'Lắp ráp và kiểm thử linh kiện RF',
    headcount: 1800,
    plants: 1,
    ownerId: 'u-am',
    contacts: [
      {
        name: 'Phạm Quốc Bảo',
        title: 'Giám đốc Vận hành',
        mail: 'bao.pham',
        phone: '0915 772 018',
        channel: 'email',
      },
    ],
  },
  {
    key: 'semv',
    name: 'Samsung Electro-Mechanics Việt Nam',
    legalName: 'Công ty TNHH Samsung Electro-Mechanics Việt Nam',
    domain: 'semv.example',
    address: 'KCN Yên Bình, Phổ Yên',
    province: 'Thái Nguyên',
    category: 'chip',
    mainProduct: 'Đế mạch FC-BGA cho chip máy chủ',
    headcount: 6000,
    plants: 1,
    ownerId: 'u-am',
    contacts: [
      {
        name: 'Lee Sang-woo',
        title: 'Giám đốc Nhà máy FC-BGA',
        mail: 'sangwoo.lee',
        phone: '0911 604 237',
        channel: 'email',
      },
      {
        name: 'Đỗ Hải Yến',
        title: 'Trưởng nhóm MES',
        mail: 'yen.do',
        phone: '0968 330 514',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'intel',
    name: 'Intel Products Việt Nam',
    legalName: 'Công ty TNHH Intel Products Việt Nam',
    domain: 'intel-vn.example',
    address: 'Lô I2, D1, Khu Công nghệ cao, TP. Thủ Đức',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Lắp ráp và kiểm thử CPU',
    headcount: 2700,
    plants: 1,
    ownerId: 'u-grace',
    contacts: [
      {
        name: 'Võ Hoàng Nam',
        title: 'Giám đốc Kỹ thuật Sản xuất',
        mail: 'nam.vo',
        phone: '0903 915 226',
        channel: 'email',
      },
      {
        name: 'Huỳnh Ngọc Trâm',
        title: 'Trưởng phòng Mua hàng',
        mail: 'tram.huynh',
        phone: '0938 402 117',
        channel: 'email',
      },
    ],
  },
  {
    key: 'luxshare',
    name: 'Luxshare-ICT Việt Nam',
    legalName: 'Công ty TNHH Luxshare-ICT Việt Nam',
    domain: 'luxshare.example',
    address: 'KCN Quang Châu, Việt Yên',
    province: 'Bắc Giang',
    category: 'chip',
    mainProduct: 'Module kết nối và SiP cho thiết bị đeo',
    headcount: 5200,
    plants: 2,
    ownerId: null,
    contacts: [
      {
        name: 'Chen Wei',
        title: 'Giám đốc Sản xuất',
        mail: 'wei.chen',
        phone: '0916 283 590',
        channel: 'email',
      },
      {
        name: 'Ngô Văn Khải',
        title: 'Trưởng phòng IT',
        mail: 'khai.ngo',
        phone: '0977 614 208',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'onsemi',
    name: 'Onsemi Việt Nam',
    legalName: 'Công ty TNHH Onsemi Việt Nam',
    domain: 'onsemi.example',
    address: 'KCN Amata, Biên Hòa',
    province: 'Đồng Nai',
    category: 'chip',
    mainProduct: 'Đóng gói linh kiện bán dẫn công suất',
    headcount: 2400,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Trương Thị Mai',
        title: 'Trưởng phòng Cải tiến',
        mail: 'mai.truong',
        phone: '0908 227 631',
        channel: 'email',
      },
    ],
  },
  {
    key: 'coherent',
    name: 'Coherent Việt Nam',
    legalName: 'Công ty TNHH Coherent Việt Nam',
    domain: 'coherent.example',
    address: 'KCN Nhơn Trạch 3, Nhơn Trạch',
    province: 'Đồng Nai',
    category: 'chip',
    mainProduct: 'Linh kiện quang và laser bán dẫn',
    headcount: 1500,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Bùi Anh Tuấn',
        title: 'Quản lý Sản xuất',
        mail: 'tuan.bui',
        phone: '0919 506 344',
        channel: 'linkedin',
      },
    ],
  },
  {
    key: 'lginnotek',
    name: 'LG Innotek Việt Nam Hải Phòng',
    legalName: 'Công ty TNHH LG Innotek Việt Nam Hải Phòng',
    domain: 'lginnotek.example',
    address: 'KCN Tràng Duệ, An Dương',
    province: 'Hải Phòng',
    category: 'chip',
    mainProduct: 'Module camera và đế mạch bán dẫn',
    headcount: 4500,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Choi Hyun-woo',
        title: 'Trưởng phòng Sản xuất',
        mail: 'hyunwoo.choi',
        phone: '0934 118 725',
        channel: 'email',
      },
      {
        name: 'Vũ Thị Lan',
        title: 'Kỹ sư IT nhà máy',
        mail: 'lan.vu',
        phone: '0962 440 813',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'jabil',
    name: 'Jabil Việt Nam',
    legalName: 'Công ty TNHH Jabil Việt Nam',
    domain: 'jabil.example',
    address: 'Khu Công nghệ cao, TP. Thủ Đức',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Lắp ráp bo mạch điện tử (EMS)',
    headcount: 3500,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Đinh Quang Vinh',
        title: 'Giám đốc Vận hành',
        mail: 'vinh.dinh',
        phone: '0907 331 952',
        channel: 'website',
      },
    ],
  },
  {
    key: 'foxconn',
    name: 'Fukang Technology (Foxconn)',
    legalName: 'Công ty TNHH Fukang Technology',
    domain: 'fukang.example',
    address: 'KCN Quang Châu, Việt Yên',
    province: 'Bắc Giang',
    category: 'chip',
    mainProduct: 'Lắp ráp linh kiện và module điện tử',
    headcount: 8000,
    plants: 2,
    ownerId: null,
    note: 'Thua ở vòng giá. Nhà máy mẹ dùng sẵn MES của một nhà cung cấp Đài Loan.',
    contacts: [
      {
        name: 'Lin Zhi-hao',
        title: 'Phó Tổng Giám đốc',
        mail: 'zhihao.lin',
        phone: '0913 870 406',
        channel: 'email',
      },
    ],
  },
  {
    key: 'hanwha',
    name: 'Hanwha Vina',
    legalName: 'Công ty TNHH Hanwha Vina',
    domain: 'hanwha.example',
    address: 'KCN Quế Võ, Quế Võ',
    province: 'Bắc Ninh',
    category: 'mechanical',
    mainProduct: 'Linh kiện cơ khí chính xác cho máy gắn chip',
    headcount: 900,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Hoàng Đức Thịnh',
        title: 'Trưởng phòng Kỹ thuật',
        mail: 'thinh.hoang',
        phone: '0918 225 470',
        channel: 'zalo-oa',
      },
    ],
  },
  {
    key: 'infineon',
    name: 'Infineon Technologies Việt Nam',
    legalName: 'Công ty TNHH Infineon Technologies Việt Nam',
    domain: 'infineon.example',
    address: 'Tòa nhà Etown Central, Quận 4',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Thiết kế và kiểm thử chip công suất',
    headcount: 450,
    plants: 0,
    ownerId: null,
    contacts: [
      {
        name: 'Lương Minh Khoa',
        title: 'Trưởng nhóm Test Engineering',
        mail: 'khoa.luong',
        phone: '0909 614 382',
        channel: 'linkedin',
      },
    ],
  },
  {
    key: 'fptsemi',
    name: 'FPT Semiconductor',
    legalName: 'Công ty TNHH Bán dẫn FPT',
    domain: 'fptsemi.example',
    address: 'Khu Công nghệ cao Đà Nẵng, Hòa Vang',
    province: 'Đà Nẵng',
    category: 'chip',
    mainProduct: 'Chip nguồn và chip IoT — chuẩn bị dây chuyền kiểm thử',
    headcount: 300,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Nguyễn Hữu Phước',
        title: 'Giám đốc Dự án Nhà máy',
        mail: 'phuoc.nguyen',
        phone: '0905 813 267',
        channel: 'website',
      },
    ],
  },
  {
    key: 'sdv',
    name: 'Samsung Display Việt Nam',
    legalName: 'Công ty TNHH Samsung Display Việt Nam',
    domain: 'sdv.example',
    address: 'KCN Yên Phong, Yên Phong',
    province: 'Bắc Ninh',
    category: 'chip',
    mainProduct: 'Tấm nền OLED và IC điều khiển màn hình',
    headcount: 12000,
    plants: 1,
    ownerId: null,
    contacts: [
      {
        name: 'Jung Eun-ji',
        title: 'Chuyên viên Mua hàng IT',
        mail: 'eunji.jung',
        phone: '0935 402 118',
        channel: 'email',
      },
    ],
  },
  {
    key: 'viettel',
    name: 'Viettel High Tech',
    legalName: 'Tổng Công ty Công nghiệp Công nghệ cao Viettel',
    domain: 'viettelhightech.example',
    address: 'Khu Công nghệ cao Hòa Lạc, Thạch Thất',
    province: 'Hà Nội',
    category: 'chip',
    mainProduct: 'Thiết kế chip 5G và thiết bị viễn thông',
    headcount: 3000,
    plants: 2,
    ownerId: null,
    contacts: [
      {
        name: 'Trần Đăng Khoa',
        title: 'Phó phòng Sản xuất',
        mail: 'khoa.tran',
        phone: '0982 336 104',
        channel: 'linkedin',
      },
    ],
  },
  {
    key: 'renesas',
    name: 'Renesas Design Việt Nam',
    legalName: 'Công ty TNHH Renesas Design Việt Nam',
    domain: 'renesas.example',
    address: 'Tòa nhà E.Town, Tân Bình',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Thiết kế vi mạch cho ô tô và công nghiệp',
    headcount: 1500,
    plants: 0,
    ownerId: null,
    contacts: [
      {
        name: 'Phan Thị Hồng',
        title: 'Trưởng phòng Hành chính',
        mail: 'hong.phan',
        phone: '0937 205 649',
        channel: 'email',
      },
    ],
  },
  {
    key: 'marvell',
    name: 'Marvell Việt Nam',
    legalName: 'Công ty TNHH Marvell Việt Nam',
    domain: 'marvell.example',
    address: 'Tòa nhà Viettel Complex, Quận 10',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Thiết kế chip hạ tầng dữ liệu',
    headcount: 500,
    plants: 0,
    ownerId: null,
    contacts: [
      {
        name: 'Đặng Minh Trí',
        title: 'Engineering Manager',
        mail: 'tri.dang',
        phone: '0906 718 293',
        channel: 'linkedin',
      },
    ],
  },
  {
    key: 'synopsys',
    name: 'Synopsys Việt Nam',
    legalName: 'Công ty TNHH Synopsys Việt Nam',
    domain: 'synopsys.example',
    address: 'Tòa nhà Pearl Plaza, Bình Thạnh',
    province: 'TP.HCM',
    category: 'chip',
    mainProduct: 'Phần mềm và IP thiết kế chip',
    headcount: 400,
    plants: 0,
    ownerId: null,
    contacts: [
      {
        name: 'Tạ Văn Hùng',
        title: 'Office Manager',
        mail: 'hung.ta',
        phone: '0901 552 870',
        channel: 'email',
      },
    ],
  },
  {
    key: 'meiko',
    name: 'Meiko Electronics Việt Nam',
    legalName: 'Công ty TNHH Meiko Electronics Việt Nam',
    domain: 'meiko.example',
    address: 'KCN Thạch Thất – Quốc Oai, Thạch Thất',
    province: 'Hà Nội',
    category: 'chip',
    mainProduct: 'Bo mạch in nhiều lớp cho điện tử ô tô',
    headcount: 4000,
    plants: 2,
    ownerId: null,
    contacts: [
      {
        name: 'Sato Kenji',
        title: 'Giám đốc Nhà máy số 2',
        mail: 'kenji.sato',
        phone: '0914 663 205',
        channel: 'email',
      },
    ],
  },
]
